### ISSUE TITLE
Deleted tokens reappear on reload (v2.1.3.1)

### ISSUE THREAD

**Issue by rinnocenti** [janssen-io/foundry-token-hotbar#15] opened 2020-06-18 21:09 UTC
when I have the mod installed,  tokens (not linked) after placing them on the map and removing or editing them the token goes back to its primary condition. (all configuration options on)

**Comment by rinnocenti** [comment] 2020-06-18 21:13
this occurs if options Share with player and lock shared is on

**Comment by janssen-io** [comment] 2020-06-19 05:31
Thanks for your report, rinnocenti.
In which version of Foundry and Token Hotbar does this occur?

Could you elaborate what you mean by “primary condition”?

**Comment by rinnocenti** [comment] 2020-06-19 05:39
FVTT: 0.6.2
HB: 2.1.3.1
I try.
I put a token (NPC) in map, and edit any position or element.
I put a second token (NPC) in map and move the first token a little.

If i close or refresh VTT, the frist token reset for frist position when i put then.
if I Delete the first (or any other token)  and refrash VTT, the token return in first position then I put (Firts condidion).

**Comment by janssen-io** [comment] 2020-06-19 07:42
Thanks for the elaboration, I have been able to reproduce the bug using your steps.

**Comment by janssen-io** [comment] 2020-06-19 07:52
I cannot reproduce this in the latest beta. So I'll put this issue on hold until that version is considered stable.

**Comment by davibraid** [comment] 2020-06-20 01:40
This is also happening to me.
I'm not sure why.

All that I did was to install Token Bar with a map open. Then I deleted a token and pressed F5 and there it was again.

**Comment by janssen-io** [comment] 2020-06-20 07:07
Also with Token Hotbar v2.1.3.1, @davibraid ?

**Comment by davibraid** [comment] 2020-06-20 18:07
Yep, but only one I have other modules on, it seems, @janssen-io 
I'll try to figure out which one is causing the issue

**Comment by janssen-io** [comment] 2020-06-20 18:09
Im 100% sure that version of Token Hotbar is causing these issues. Currently working hard to get the latest beta stable enough to release.

**Comment by janssen-io** [comment] 2020-06-26 14:27
@davibraid and @rinnocenti , can you guys verify if this issue is fixed in the latest release? (v3.1.0)

**Comment by rinnocenti** [comment] 2020-06-26 15:42
it is no longer duplicated, but it is no longer making the hot bar.
I only tested non-linked tokens, but this is no longer making the bars individually. (not actually maintaining any actions on tab 5)

**Comment by janssen-io** [comment] 2020-06-26 16:33
Is that still on Foundry 062 or on 064?
And just a sanity check: your settings are set to page 5?
Also, you don’t use Norcs Custom Hotbar right?

**Comment by rinnocenti** [comment] 2020-06-26 16:58
064.
setting page 5.
I',m not use Norcs Custom Hotbar.

**Comment by janssen-io** [comment] 2020-06-26 20:55
Alright, thanks for the info. I’ll investigate :)

**Comment by janssen-io** [comment] 2020-06-26 22:35
Found the issue, @rinnocenti. You should be able to update to 3.1.1 for a fix :)

**Closed** 2020-06-28 12:51 UTC
Labels: bug, fixed in beta
